import { Redirect, useLocalSearchParams, useRouter } from "expo-router";
import {
  collection,
  doc,
  getDoc,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  where,
  type DocumentData,
} from "firebase/firestore";
import { useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";

import {
  CONTROL_SIZE,
  FONT_SIZE,
  RADIUS,
  SPACING,
  type ThemeColors,
} from "@/constants/theme";
import { CancelInputIcon } from "@/components/icons/cancel-input-icon";
import {
  CATEGORIES_COLLECTION,
  POSTS_COLLECTION,
  createSlug,
  getPostCardThumbnailUrl,
  getYouTubeVideoId,
  isValidOptionalHttpUrl,
  mapCategoryRecord,
  mapPostRecord,
  sortPostsByRecency,
  type CategoryRecord,
  type PostRecord,
  type PostStatus,
} from "@/lib/content";
import { getEffectiveUserRole } from "@/lib/access";
import { firestore } from "@/lib/firebase";
import { getActionErrorMessage, getRequestErrorMessage } from "@/lib/network";
import { notifyPostPublishedAsync } from "@/lib/notifications";
import { useAuth } from "@/providers/auth-provider";
import { useNetworkStatus } from "@/providers/network-provider";
import { useAppTheme } from "@/providers/theme-provider";

const POST_STATUSES: PostStatus[] = ["draft", "pending", "published"];
const HTML_TAG_PATTERN = /<\/?[a-z][\s\S]*>/i;
type PostEditorField =
  | "title"
  | "slug"
  | "content"
  | "featureImageUrl"
  | "youtubeVideoUrl"
  | "category";
type PostEditorFieldErrors = Partial<Record<PostEditorField, string>>;

const getStatusLabel = (status: PostStatus) => {
  if (status === "pending") {
    return "Pending Review";
  }

  return status === "published" ? "Published" : "Draft";
};

const resolvePostId = (value: string | string[] | undefined) =>
  typeof value === "string" ? value : "";

const toHtmlContent = (value: string) => {
  const normalized = value.trim();
  if (!normalized) {
    return "";
  }

  if (HTML_TAG_PATTERN.test(normalized)) {
    return normalized;
  }

  const escaped = normalized
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return `<p>${escaped.replace(/\n/g, "<br/>")}</p>`;
};

const extractPlainText = (value: string) =>
  value
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#39;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/\u200B/g, "")
    .replace(/\s+/g, " ")
    .trim();

export default function AdminPostEditScreen() {
  const { colors, resolvedTheme } = useAppTheme();
  const { isConnected, showToast } = useNetworkStatus();
  const router = useRouter();
  const { postId: postIdParam } = useLocalSearchParams<{ postId?: string }>();
  const { canManagePosts, canModeratePosts, profile, role, user } = useAuth();
  const styles = createStyles(colors, resolvedTheme);

  const postId = resolvePostId(postIdParam);
  const isEditing = Boolean(postId);

  const [categories, setCategories] = useState<CategoryRecord[]>([]);
  const [posts, setPosts] = useState<PostRecord[]>([]);
  const [isLoadingCategories, setIsLoadingCategories] = useState(true);
  const [isLoadingPost, setIsLoadingPost] = useState(isEditing);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [fieldErrors, setFieldErrors] = useState<PostEditorFieldErrors>({});

  const [title, setTitle] = useState("");
  const [slugInput, setSlugInput] = useState("");
  const [isSlugManuallyEdited, setIsSlugManuallyEdited] = useState(false);
  const [contentPlainText, setContentPlainText] = useState("");
  const [featureImageUrl, setFeatureImageUrl] = useState("");
  const [youtubeVideoUrl, setYoutubeVideoUrl] = useState("");
  const [category, setCategory] = useState("");
  const [status, setStatus] = useState<PostStatus>("draft");
  const [isCategoryMenuOpen, setIsCategoryMenuOpen] = useState(false);
  const [existingPostRecord, setExistingPostRecord] = useState<PostRecord | null>(null);

  const autoGeneratedSlug = useMemo(() => createSlug(title), [title]);
  const selectedCategoryLabel = useMemo(() => {
    const selectedCategory = categories.find((item) => item.slug === category);
    if (!selectedCategory) {
      return "";
    }
    return selectedCategory.slug;
  }, [categories, category]);
  const authorSnapshot = useMemo(
    () => ({
      authorId: user?.uid ?? "",
      authorRole: role,
      authorDisplayName:
        profile?.displayName ||
        user?.displayName ||
        profile?.username ||
        profile?.email ||
        user?.email ||
        "User",
      authorUsername: profile?.username ?? "",
      authorPhotoURL: profile?.photoURL || user?.photoURL || "",
      authorEmail: profile?.email || user?.email || "",
    }),
    [
      profile?.displayName,
      profile?.email,
      profile?.photoURL,
      profile?.username,
      role,
      user?.displayName,
      user?.email,
      user?.photoURL,
      user?.uid,
    ],
  );

  useEffect(() => {
    setIsLoadingCategories(true);

    if (!canModeratePosts && !user?.uid) {
      setPosts([]);
      setIsLoadingCategories(false);
      setIsLoadingPost(false);
      return;
    }

    const categoriesQuery = query(
      collection(firestore, CATEGORIES_COLLECTION),
      orderBy("name", "asc"),
    );
    const postsQuery = canModeratePosts
      ? query(collection(firestore, POSTS_COLLECTION))
      : query(
          collection(firestore, POSTS_COLLECTION),
          where("createdBy", "==", user?.uid ?? ""),
        );

    const unsubscribeCategories = onSnapshot(
      categoriesQuery,
      (snapshot) => {
        setCategories(
          snapshot.docs.map((item) =>
            mapCategoryRecord(item.id, item.data() as DocumentData),
          ),
        );
        setIsLoadingCategories(false);
        setError("");
      },
      (snapshotError) => {
        setIsLoadingCategories(false);
        setError(
          getRequestErrorMessage({
            error: snapshotError,
            isConnected,
            onlineMessage: "Unable to load categories.",
          }),
        );
      },
    );

    const unsubscribePosts = onSnapshot(
      postsQuery,
      (snapshot) => {
        setPosts(
          sortPostsByRecency(
            snapshot.docs.map((item) =>
              mapPostRecord(item.id, item.data() as DocumentData),
            ),
          ),
        );
        setError("");
      },
      (snapshotError) => {
        setError(
          getRequestErrorMessage({
            error: snapshotError,
            isConnected,
            onlineMessage: "Unable to load posts for validation.",
          }),
        );
      },
    );

    return () => {
      unsubscribeCategories();
      unsubscribePosts();
    };
  }, [canModeratePosts, isConnected, user?.uid]);

  useEffect(() => {
    if (!isEditing) {
      setExistingPostRecord(null);
      setFeatureImageUrl("");
      setYoutubeVideoUrl("");
      setIsLoadingPost(false);
      return;
    }

    let active = true;

    const hydratePost = async () => {
      try {
        const postRef = doc(firestore, POSTS_COLLECTION, postId);
        const snapshot = await getDoc(postRef);

        if (!snapshot.exists()) {
          if (active) {
            setError("Post not found.");
          }
          return;
        }

        const rawData = snapshot.data() as DocumentData;
        let post = mapPostRecord(snapshot.id, rawData);

        if (!post.hasAuthorRole && post.authorId) {
          const authorProfileSnapshot = await getDoc(doc(firestore, "users", post.authorId));

          if (authorProfileSnapshot.exists()) {
            const authorData = authorProfileSnapshot.data() as DocumentData;
            post = {
              ...post,
              authorRole: getEffectiveUserRole(
                typeof authorData?.role === "string" ? authorData.role : "",
              ),
              hasAuthorRole: true,
            };
          }
        }

        if (!active) {
          return;
        }

        const isOwnedByCurrentUser =
          post.createdBy === user?.uid || (!!user?.email && post.createdByEmail === user.email);

        if (!canModeratePosts && !isOwnedByCurrentUser) {
          setError("You can edit only the posts created by your account.");
          setIsLoadingPost(false);
          router.replace("/admin/posts");
          return;
        }

        setTitle(post.title);
        setExistingPostRecord(post);
        setSlugInput(post.slug);
        setIsSlugManuallyEdited(post.slug !== createSlug(post.title));
        const hydratedContentHtml =
          typeof rawData.contentHtml === "string" && rawData.contentHtml.trim()
            ? rawData.contentHtml
            : toHtmlContent(post.content);
        const hydratedPlainText =
          post.content.trim() || extractPlainText(hydratedContentHtml);
        setContentPlainText(hydratedPlainText);
        setFeatureImageUrl(post.featureImageUrl);
        setYoutubeVideoUrl(post.youtubeVideoUrl);
        setCategory(post.category);
        setStatus(post.status);
        setError("");
      } catch (loadError) {
        if (active) {
          setError(
            getRequestErrorMessage({
              error: loadError,
              isConnected,
              onlineMessage: "Unable to load post details.",
            }),
          );
        }
      } finally {
        if (active) {
          setIsLoadingPost(false);
        }
      }
    };

    void hydratePost();

    return () => {
      active = false;
    };
  }, [canModeratePosts, isConnected, isEditing, postId, router, user?.email, user?.uid]);

  useEffect(() => {
    if (!isSlugManuallyEdited) {
      setSlugInput(autoGeneratedSlug);
    }
  }, [autoGeneratedSlug, isSlugManuallyEdited]);

  useEffect(() => {
    if (!categories.length) {
      setIsCategoryMenuOpen(false);
      return;
    }

    if (!category || !categories.some((item) => item.slug === category)) {
      setCategory(categories[0].slug);
    }
  }, [categories, category]);

  const isLoadingInitial = isLoadingCategories || isLoadingPost;

  if (!canManagePosts) {
    return <Redirect href="/settings" />;
  }

  const getUniqueSlug = (base: string) => {
    const normalizedBase = base || "post";
    let candidate = normalizedBase;
    let suffix = 1;

    while (
      posts.some((item) => item.slug === candidate && item.id !== postId)
    ) {
      candidate = `${normalizedBase}-${suffix}`;
      suffix += 1;
    }

    return candidate;
  };

  const clearFeedback = () => {
    setError("");
    setSuccess("");
  };

  const clearFieldError = (field: PostEditorField) => {
    setFieldErrors((current) => {
      if (!current[field]) {
        return current;
      }

      const next = { ...current };
      delete next[field];
      return next;
    });
  };

  const handleCloseEditor = () => {
    router.replace("/admin/posts");
  };

  const setSingleFieldError = (field: PostEditorField, message: string) => {
    setFieldErrors({ [field]: message });
    setSuccess("");
  };

  const handleTitleChange = (value: string) => {
    setTitle(value);
    clearFieldError("title");
    clearFeedback();
  };

  const handleSlugChange = (value: string) => {
    setSlugInput(value);
    const normalized = createSlug(value);
    setIsSlugManuallyEdited(
      Boolean(value.trim()) && normalized !== autoGeneratedSlug,
    );
    clearFieldError("slug");
    clearFeedback();
  };

  const handleResetSlug = () => {
    setIsSlugManuallyEdited(false);
    setSlugInput(autoGeneratedSlug);
    clearFieldError("slug");
    clearFeedback();
  };

  const handleSelectCategory = (value: string) => {
    setCategory(value);
    setIsCategoryMenuOpen(false);
    clearFieldError("category");
    clearFeedback();
  };

  const handleFeatureImageUrlChange = (value: string) => {
    setFeatureImageUrl(value);
    clearFieldError("featureImageUrl");
    clearFeedback();
  };

  const handleYoutubeVideoUrlChange = (value: string) => {
    setYoutubeVideoUrl(value);
    clearFieldError("youtubeVideoUrl");
    clearFeedback();
  };

  const handleContentChange = (value: string) => {
    setContentPlainText(value);
    clearFieldError("content");
    clearFeedback();
  };

  const renderClearInputButton = ({
    value,
    onPress,
    accessibilityLabel,
    hasError = false,
    contentAligned = false,
  }: {
    value: string;
    onPress: () => void;
    accessibilityLabel: string;
    hasError?: boolean;
    contentAligned?: boolean;
  }) => {
    if (!value) {
      return null;
    }

    return (
      <TouchableOpacity
        accessibilityRole="button"
        accessibilityLabel={accessibilityLabel}
        style={[
          styles.inputClearButton,
          hasError ? styles.inputClearButtonError : undefined,
          contentAligned ? styles.inputClearButtonContentAligned : undefined,
        ]}
        activeOpacity={0.72}
        onPress={onPress}
        hitSlop={8}
      >
        <CancelInputIcon color={hasError ? colors.danger : colors.text} />
      </TouchableOpacity>
    );
  };

  const handleSave = async (mode: "draft" | "submit" | "save") => {
    const trimmedTitle = title.trim();
    const plainContent = contentPlainText.trim();
    const htmlContent = toHtmlContent(plainContent);
    const normalizedFeatureImageUrl = featureImageUrl.trim();
    const normalizedYoutubeVideoUrl = youtubeVideoUrl.trim();
    const persistedFeatureImageUrl = normalizedFeatureImageUrl;
    const persistedYoutubeVideoUrl =
      isEditing && !normalizedYoutubeVideoUrl
        ? existingPostRecord?.youtubeVideoUrl ?? ""
        : normalizedYoutubeVideoUrl;
    const normalizedCategory = category.trim().toLowerCase();
    const normalizedStatus: PostStatus = canModeratePosts
      ? status
      : mode === "submit"
        ? "pending"
        : "draft";
    const slugBase = createSlug(slugInput || trimmedTitle);
    setFieldErrors({});

    if (!trimmedTitle) {
      setError("");
      setSingleFieldError("title", "Title is required.");
      return;
    }

    if (!plainContent) {
      setError("");
      setSingleFieldError("content", "Blog content is required.");
      return;
    }

    if (!isValidOptionalHttpUrl(persistedFeatureImageUrl)) {
      setError("");
      setSingleFieldError(
        "featureImageUrl",
        "Feature image URL must be a valid http/https link.",
      );
      return;
    }

    if (!isValidOptionalHttpUrl(persistedYoutubeVideoUrl)) {
      setError("");
      setSingleFieldError(
        "youtubeVideoUrl",
        "YouTube video URL must be a valid http/https link.",
      );
      return;
    }

    if (
      persistedYoutubeVideoUrl &&
      !getYouTubeVideoId(persistedYoutubeVideoUrl)
    ) {
      setError("");
      setSingleFieldError("youtubeVideoUrl", "Enter a valid YouTube video link.");
      return;
    }

    if (!categories.length) {
      setError("");
      setSingleFieldError("category", "Create at least one category before saving a post.");
      return;
    }

    if (!slugBase) {
      setError("");
      setSingleFieldError("slug", "Slug must include letters or numbers.");
      return;
    }

    if (
      !normalizedCategory ||
      !categories.some((item) => item.slug === normalizedCategory)
    ) {
      setError("");
      setSingleFieldError("category", "Select a valid category.");
      return;
    }

    try {
      setIsSubmitting(true);
      clearFeedback();
      setFieldErrors({});
      const isOwnerEditingOwnPost =
        !existingPostRecord ||
        existingPostRecord.authorId === authorSnapshot.authorId ||
        existingPostRecord.createdBy === authorSnapshot.authorId;
      const persistedAuthor = isOwnerEditingOwnPost
        ? {
            authorId: authorSnapshot.authorId,
            authorRole: authorSnapshot.authorRole,
            authorDisplayName: authorSnapshot.authorDisplayName,
            authorUsername: authorSnapshot.authorUsername,
            authorPhotoURL: authorSnapshot.authorPhotoURL,
            createdBy: authorSnapshot.authorId,
            createdByEmail: authorSnapshot.authorEmail,
          }
        : {
            authorId: existingPostRecord.authorId,
            authorRole: existingPostRecord.authorRole,
            authorDisplayName: existingPostRecord.authorDisplayName,
            authorUsername: existingPostRecord.authorUsername,
            authorPhotoURL: existingPostRecord.authorPhotoURL,
            createdBy: existingPostRecord.createdBy,
            createdByEmail: existingPostRecord.createdByEmail,
          };
      const moderationFields =
        normalizedStatus === "published"
          ? {
              submittedAt: existingPostRecord?.submittedAt || serverTimestamp(),
              publishedAt: serverTimestamp(),
              approvedAt: serverTimestamp(),
              approvedBy: user?.uid ?? "",
              approvedByEmail: user?.email ?? "",
            }
          : normalizedStatus === "pending"
            ? {
                submittedAt: serverTimestamp(),
                publishedAt: null,
                approvedAt: null,
                approvedBy: null,
                approvedByEmail: null,
              }
            : {
                submittedAt: null,
                publishedAt: null,
                approvedAt: null,
                approvedBy: null,
                approvedByEmail: null,
              };
      const notificationImageUrl = getPostCardThumbnailUrl({
        featureImageUrl: persistedFeatureImageUrl,
        youtubeVideoUrl: persistedYoutubeVideoUrl,
      });

      if (isEditing) {
        const uniqueSlug = getUniqueSlug(slugBase);
        const postRef = doc(firestore, POSTS_COLLECTION, postId);
        const shouldNotifyOnPublish =
          normalizedStatus === "published" &&
          existingPostRecord?.status !== "published";

        await setDoc(
          postRef,
          {
            id: postId,
            slug: uniqueSlug,
            title: trimmedTitle,
            content: plainContent,
            contentHtml: htmlContent,
            featureImageUrl: persistedFeatureImageUrl,
            youtubeVideoUrl: persistedYoutubeVideoUrl,
            category: normalizedCategory,
            status: normalizedStatus,
            uploadDate: serverTimestamp(),
            authorId: persistedAuthor.authorId,
            authorRole: persistedAuthor.authorRole,
            authorDisplayName: persistedAuthor.authorDisplayName,
            authorUsername: persistedAuthor.authorUsername,
            authorPhotoURL: persistedAuthor.authorPhotoURL,
            updatedBy: user?.uid ?? "",
            updatedByEmail: user?.email ?? "",
            ...moderationFields,
          },
          { merge: true },
        );

        setSuccess(
          normalizedStatus === "pending"
            ? "Post updated and submitted for review."
            : normalizedStatus === "published"
              ? "Post updated and published."
              : "Draft updated successfully."
        );

        if (shouldNotifyOnPublish) {
          void notifyPostPublishedAsync({
            authorUid: persistedAuthor.authorId,
            actorUid: user?.uid,
            postId,
            postTitle: trimmedTitle,
            postContent: plainContent,
            imageUrl: notificationImageUrl,
          }).catch((notificationError) => {
            console.warn("Unable to send publish notification.", notificationError);
            showToast("Post published, but notification could not be delivered.");
          });
        }
      } else {
        const postRef = doc(collection(firestore, POSTS_COLLECTION));
        const uniqueSlug = getUniqueSlug(slugBase);

        await setDoc(postRef, {
          id: postRef.id,
          slug: uniqueSlug,
          title: trimmedTitle,
          content: plainContent,
          contentHtml: htmlContent,
          featureImageUrl: persistedFeatureImageUrl,
          youtubeVideoUrl: persistedYoutubeVideoUrl,
          category: normalizedCategory,
          status: normalizedStatus,
          createDate: serverTimestamp(),
          uploadDate: serverTimestamp(),
          authorId: authorSnapshot.authorId,
          authorRole: authorSnapshot.authorRole,
          authorDisplayName: authorSnapshot.authorDisplayName,
          authorUsername: authorSnapshot.authorUsername,
          authorPhotoURL: authorSnapshot.authorPhotoURL,
          createdBy: authorSnapshot.authorId,
          createdByEmail: authorSnapshot.authorEmail,
          updatedBy: user?.uid ?? "",
          updatedByEmail: user?.email ?? "",
          ...moderationFields,
        });

        setSuccess(
          normalizedStatus === "pending"
            ? "Post created and submitted for review."
            : normalizedStatus === "published"
              ? "Post created and published."
              : "Draft created successfully."
        );

        if (normalizedStatus === "published") {
          void notifyPostPublishedAsync({
            authorUid: authorSnapshot.authorId,
            actorUid: user?.uid,
            postId: postRef.id,
            postTitle: trimmedTitle,
            postContent: plainContent,
            imageUrl: notificationImageUrl,
          }).catch((notificationError) => {
            console.warn("Unable to send publish notification.", notificationError);
            showToast("Post published, but notification could not be delivered.");
          });
        }
      }

      router.replace("/admin/posts");
    } catch (saveError) {
      setError(
        getActionErrorMessage({
          error: saveError,
          isConnected,
          fallbackMessage: "Unable to save post to Firebase.",
        }),
      );
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoadingInitial) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={colors.primary} />
      </View>
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <View style={styles.pageHeader}>
        <Text style={styles.title}>
          {isEditing ? "Edit Post" : "Create Post"}
        </Text>
      </View>
      {error ? <View style={styles.errorBanner}><Text style={styles.error}>{error}</Text></View> : null}
      {success ? <Text style={styles.success}>{success}</Text> : null}

      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Basics</Text>
        </View>
        <View style={styles.sectionDivider} />

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Title *</Text>
          <View
            style={[
              styles.inputWrap,
              styles.inputWrapWithAction,
              fieldErrors.title ? styles.inputWrapError : undefined,
            ]}
          >
            <TextInput
              value={title}
              onChangeText={handleTitleChange}
              placeholder="Enter title"
              placeholderTextColor={colors.mutedText}
              style={[styles.input, styles.inputWithAction]}
            />
            {renderClearInputButton({
              value: title,
              onPress: () => handleTitleChange(""),
              accessibilityLabel: "Clear title",
              hasError: Boolean(fieldErrors.title),
            })}
          </View>
          {fieldErrors.title ? (
            <Text style={styles.fieldError}>{fieldErrors.title}</Text>
          ) : null}
        </View>

        <View style={styles.fieldGroup}>
          <View style={styles.inlineRow}>
            <Text style={styles.label}>Slug</Text>
            <Pressable onPress={handleResetSlug}>
              <Text style={styles.linkText}>Reset Auto Slug</Text>
            </Pressable>
          </View>
          <View
            style={[
              styles.inputWrap,
              styles.inputWrapWithAction,
              fieldErrors.slug ? styles.inputWrapError : undefined,
            ]}
          >
            <TextInput
              value={slugInput}
              onChangeText={handleSlugChange}
              placeholder="Auto-generated from title"
              placeholderTextColor={colors.mutedText}
              autoCapitalize="none"
              style={[styles.input, styles.inputWithAction]}
            />
            {renderClearInputButton({
              value: slugInput,
              onPress: () => handleSlugChange(""),
              accessibilityLabel: "Clear slug",
              hasError: Boolean(fieldErrors.slug),
            })}
          </View>
          {fieldErrors.slug ? (
            <Text style={styles.fieldError}>{fieldErrors.slug}</Text>
          ) : null}
        </View>
      </View>

      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Content</Text>
        </View>
        <View style={styles.sectionDivider} />

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Blog Content *</Text>
          <View
            style={[
              styles.inputWrap,
              styles.contentInputWrap,
              fieldErrors.content ? styles.inputWrapError : undefined,
            ]}
          >
            <TextInput
              value={contentPlainText}
              onChangeText={handleContentChange}
              placeholder="Write your blog post here..."
              placeholderTextColor={colors.mutedText}
              style={[
                styles.input,
                styles.contentInput,
                styles.contentInputWithAction,
              ]}
              multiline
              textAlignVertical="top"
            />
            {renderClearInputButton({
              value: contentPlainText,
              onPress: () => handleContentChange(""),
              accessibilityLabel: "Clear blog content",
              hasError: Boolean(fieldErrors.content),
              contentAligned: true,
            })}
          </View>
          {fieldErrors.content ? (
            <Text style={styles.fieldError}>{fieldErrors.content}</Text>
          ) : null}
        </View>
      </View>

      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Media</Text>
        </View>
        <View style={styles.sectionDivider} />

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Feature Image URL</Text>
          <View
            style={[
              styles.inputWrap,
              styles.inputWrapWithAction,
              fieldErrors.featureImageUrl ? styles.inputWrapError : undefined,
            ]}
          >
            <TextInput
              value={featureImageUrl}
              onChangeText={handleFeatureImageUrlChange}
              placeholder=""
              placeholderTextColor={colors.mutedText}
              autoCapitalize="none"
              autoCorrect={false}
              style={[styles.input, styles.inputWithAction]}
            />
            {renderClearInputButton({
              value: featureImageUrl,
              onPress: () => handleFeatureImageUrlChange(""),
              accessibilityLabel: "Clear feature image URL",
              hasError: Boolean(fieldErrors.featureImageUrl),
            })}
          </View>
          {fieldErrors.featureImageUrl ? (
            <Text style={styles.fieldError}>{fieldErrors.featureImageUrl}</Text>
          ) : null}
        </View>

        <View style={styles.fieldSeparator} />

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>YouTube Video URL</Text>
          <View
            style={[
              styles.inputWrap,
              styles.inputWrapWithAction,
              fieldErrors.youtubeVideoUrl ? styles.inputWrapError : undefined,
            ]}
          >
            <TextInput
              value={youtubeVideoUrl}
              onChangeText={handleYoutubeVideoUrlChange}
              placeholder=""
              placeholderTextColor={colors.mutedText}
              autoCapitalize="none"
              autoCorrect={false}
              style={[styles.input, styles.inputWithAction]}
            />
            {renderClearInputButton({
              value: youtubeVideoUrl,
              onPress: () => handleYoutubeVideoUrlChange(""),
              accessibilityLabel: "Clear YouTube video URL",
              hasError: Boolean(fieldErrors.youtubeVideoUrl),
            })}
          </View>
          {fieldErrors.youtubeVideoUrl ? (
            <Text style={styles.fieldError}>{fieldErrors.youtubeVideoUrl}</Text>
          ) : null}
        </View>
      </View>

      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Text style={styles.sectionTitle}>Publishing</Text>
        </View>
        <View style={styles.sectionDivider} />

        <View style={styles.fieldGroup}>
          {canModeratePosts ? (
            <>
              <Text style={styles.label}>Status</Text>
              <View style={styles.chipRow}>
                {POST_STATUSES.map((item) => (
                  <Pressable
                    key={item}
                    style={[
                      styles.chip,
                      status === item ? styles.chipActive : undefined,
                    ]}
                    onPress={() => setStatus(item)}
                  >
                    <Text
                      style={[
                        styles.chipText,
                        status === item ? styles.chipTextActive : undefined,
                      ]}
                    >
                      {getStatusLabel(item)}
                    </Text>
                  </Pressable>
                ))}
              </View>
            </>
          ) : (
            <>
              <Text style={styles.label}>Status</Text>
              <View style={styles.readonlyCard}>
                <Text style={styles.readonlyValue}>{getStatusLabel(status)}</Text>
              </View>
              {isEditing && status === "published" ? (
                <Text style={styles.helperText}>
                  Editing a live post and submitting it again will move it back into review.
                </Text>
              ) : null}
            </>
          )}
        </View>

        <View style={styles.fieldSeparator} />

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Category *</Text>
          <TouchableOpacity
            style={[
              styles.categoryTrigger,
              fieldErrors.category ? styles.inputWrapError : undefined,
              (!categories.length || isSubmitting) && styles.triggerDisabled,
            ]}
            activeOpacity={0.85}
            onPress={() => {
              if (!categories.length || isSubmitting) {
                return;
              }
              setIsCategoryMenuOpen(true);
            }}
            disabled={!categories.length || isSubmitting}
          >
            <View style={styles.categoryTriggerContent}>
              <Text
                style={[
                  styles.categoryTriggerValue,
                  !selectedCategoryLabel && styles.dropdownPlaceholder,
                ]}
              >
                {selectedCategoryLabel ||
                  (isLoadingCategories
                    ? "Loading categories..."
                    : "Select category")}
              </Text>
            </View>
            <Text style={styles.categoryTriggerAction}>Change</Text>
          </TouchableOpacity>
          {fieldErrors.category ? (
            <Text style={styles.fieldError}>{fieldErrors.category}</Text>
          ) : null}
        </View>
      </View>

      <View style={styles.buttonGroup}>
        <View style={styles.buttonRow}>
          {canModeratePosts ? (
            <TouchableOpacity
              style={[
                styles.primaryButton,
                isSubmitting && styles.buttonDisabled,
              ]}
              activeOpacity={0.85}
              onPress={() => {
                void handleSave("save");
              }}
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <ActivityIndicator size="small" color={colors.primaryText} />
              ) : (
                <Text style={styles.primaryButtonText}>
                  {isEditing ? "Save Changes" : "Create Post"}
                </Text>
              )}
            </TouchableOpacity>
          ) : (
            <>
              <TouchableOpacity
                style={[
                  styles.secondaryButton,
                  isSubmitting && styles.buttonDisabled,
                ]}
                activeOpacity={0.85}
                onPress={() => {
                  void handleSave("draft");
                }}
                disabled={isSubmitting}
              >
                <Text style={styles.secondaryButtonText}>
                  {isEditing ? "Save Draft" : "Create Draft"}
                </Text>
              </TouchableOpacity>

              <TouchableOpacity
                style={[
                  styles.primaryButton,
                  isSubmitting && styles.buttonDisabled,
                ]}
                activeOpacity={0.85}
                onPress={() => {
                  void handleSave("submit");
                }}
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <ActivityIndicator size="small" color={colors.primaryText} />
                ) : (
                  <Text style={styles.primaryButtonText}>
                    {isEditing ? "Update & Submit" : "Submit for Review"}
                  </Text>
                )}
              </TouchableOpacity>
            </>
          )}
        </View>

        <TouchableOpacity
          style={[
            styles.secondaryButton,
            styles.backButton,
            isSubmitting && styles.buttonDisabled,
          ]}
          activeOpacity={0.85}
          onPress={handleCloseEditor}
          disabled={isSubmitting}
        >
          <Text style={styles.secondaryButtonText}>Back to Post List</Text>
        </TouchableOpacity>
      </View>

      <Modal
        animationType="slide"
        transparent
        visible={isCategoryMenuOpen}
        onRequestClose={() => setIsCategoryMenuOpen(false)}
      >
        <View style={styles.selectorRoot}>
          <Pressable
            style={styles.selectorBackdrop}
            onPress={() => setIsCategoryMenuOpen(false)}
          />
          <View style={styles.selectorSheet}>
            <View style={styles.selectorHandle} />
            <View style={styles.selectorHeader}>
              <Text style={styles.selectorTitle}>Select Category</Text>
              <TouchableOpacity
                style={styles.selectorCloseButton}
                activeOpacity={0.85}
                onPress={() => setIsCategoryMenuOpen(false)}
              >
                <Text style={styles.selectorCloseText}>Close</Text>
              </TouchableOpacity>
            </View>

            <ScrollView
              style={styles.selectorList}
              contentContainerStyle={styles.selectorListContent}
              showsVerticalScrollIndicator={false}
            >
              {categories.map((item) => (
                <TouchableOpacity
                  key={item.id}
                  style={[
                    styles.selectorOption,
                    category === item.slug ? styles.selectorOptionActive : undefined,
                  ]}
                  activeOpacity={0.85}
                  onPress={() => handleSelectCategory(item.slug)}
                >
                  <View style={styles.selectorOptionContent}>
                    <Text
                      style={[
                        styles.selectorOptionTitle,
                        category === item.slug ? styles.selectorOptionTitleActive : undefined,
                      ]}
                    >
                      {item.slug}
                    </Text>
                  </View>
                  {category === item.slug ? (
                    <View style={styles.selectorBadge}>
                      <Text style={styles.selectorBadgeText}>Selected</Text>
                    </View>
                  ) : null}
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>
        </View>
      </Modal>
    </ScrollView>
  );
}

const createStyles = (colors: ThemeColors, resolvedTheme: "light" | "dark") => {
  const outlineColor = resolvedTheme === "dark" ? colors.divider : colors.border;
  const activeOptionBackground =
    resolvedTheme === "dark" ? colors.accentSoft : colors.activeSurface;

  return StyleSheet.create({
    loadingContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.background,
    },
    container: {
      padding: SPACING.xl,
      backgroundColor: colors.background,
      gap: SPACING.lg,
    },
    pageHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: SPACING.md,
    },
    title: {
      flex: 1,
      fontSize: FONT_SIZE.title,
      fontWeight: "700",
      color: colors.text,
    },
    errorBanner: {
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: colors.dangerBorder,
      backgroundColor: colors.dangerSoft,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.sm,
    },
    error: {
      color: colors.danger,
      fontSize: 13,
      lineHeight: 18,
    },
    success: {
      color: colors.success,
      fontSize: 13,
    },
    section: {
      backgroundColor: colors.surface,
      borderRadius: RADIUS.lg,
      padding: SPACING.lg,
      gap: SPACING.md,
    },
    sectionHeader: {
      gap: SPACING.xs,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: colors.text,
    },
    sectionDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
    },
    fieldGroup: {
      gap: SPACING.sm,
    },
    fieldSeparator: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.divider,
    },
    inlineRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: SPACING.sm,
    },
    helperText: {
      color: colors.mutedText,
      fontSize: 12,
      lineHeight: 18,
    },
    fieldError: {
      color: colors.danger,
      fontSize: 12,
      lineHeight: 18,
    },
    linkText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: "600",
    },
    inputWrap: {
      minHeight: CONTROL_SIZE.inputHeight,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: outlineColor,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: SPACING.md,
      justifyContent: "center",
    },
    inputWrapWithAction: {
      flexDirection: "row",
      alignItems: "center",
      gap: SPACING.sm,
    },
    inputWrapError: {
      borderColor: colors.dangerBorder,
      backgroundColor: colors.dangerSoft,
    },
    contentInputWrap: {
      justifyContent: "flex-start",
      position: "relative",
      paddingTop: SPACING.sm,
      paddingBottom: SPACING.sm,
    },
    input: {
      color: colors.text,
      fontSize: FONT_SIZE.button,
    },
    inputWithAction: {
      flex: 1,
    },
    contentInputWithAction: {
      paddingRight: CONTROL_SIZE.inputHeight,
      paddingBottom: CONTROL_SIZE.inputHeight * 0.5,
    },
    inputClearButton: {
      alignItems: "center",
      justifyContent: "center",
      padding: 2,
    },
    inputClearButtonError: {
      opacity: 0.9,
    },
    inputClearButtonContentAligned: {
      position: "absolute",
      bottom: SPACING.sm,
      right: SPACING.sm,
    },
    readonlyCard: {
      minHeight: CONTROL_SIZE.inputHeight,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: outlineColor,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: SPACING.md,
      justifyContent: "center",
    },
    readonlyValue: {
      color: colors.text,
      fontSize: FONT_SIZE.button,
      fontWeight: "600",
    },
    contentInput: {
      minHeight: 180,
      paddingVertical: SPACING.md,
    },
    label: {
      color: colors.text,
      fontWeight: "600",
    },
    chipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: SPACING.sm,
    },
    chip: {
      borderWidth: 1,
      borderColor: outlineColor,
      borderRadius: 999,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs,
      backgroundColor: colors.surface,
    },
    chipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    chipText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "600",
    },
    chipTextActive: {
      color: colors.primaryText,
    },
    categoryTrigger: {
      minHeight: CONTROL_SIZE.inputHeight,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: outlineColor,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.md,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: SPACING.sm,
    },
    categoryTriggerContent: {
      flex: 1,
      gap: 4,
    },
    categoryTriggerValue: {
      color: colors.text,
      fontSize: FONT_SIZE.button,
      flex: 1,
      fontWeight: "600",
    },
    categoryTriggerAction: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    triggerDisabled: {
      opacity: 0.6,
    },
    dropdownPlaceholder: {
      color: colors.mutedText,
    },
    selectorRoot: {
      flex: 1,
      justifyContent: "flex-end",
    },
    selectorBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: colors.overlay,
    },
    selectorSheet: {
      borderTopLeftRadius: RADIUS.lg,
      borderTopRightRadius: RADIUS.lg,
      borderWidth: 1,
      borderColor: outlineColor,
      backgroundColor: colors.surface,
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.sm,
      paddingBottom: SPACING.xl,
      gap: SPACING.md,
      maxHeight: "72%",
    },
    selectorHandle: {
      alignSelf: "center",
      width: 44,
      height: 4,
      borderRadius: 999,
      backgroundColor: colors.divider,
    },
    selectorHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: SPACING.md,
    },
    selectorTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: "700",
    },
    selectorCloseButton: {
      minHeight: 38,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: outlineColor,
      paddingHorizontal: SPACING.md,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surfaceMuted,
    },
    selectorCloseText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "700",
    },
    selectorList: {
      flexGrow: 0,
    },
    selectorListContent: {
      gap: SPACING.sm,
    },
    selectorOption: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: SPACING.md,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: outlineColor,
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.md,
      backgroundColor: colors.surface,
    },
    selectorOptionActive: {
      backgroundColor: activeOptionBackground,
      borderColor: colors.accentBorder,
    },
    selectorOptionContent: {
      flex: 1,
      gap: 2,
    },
    selectorOptionTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
    },
    selectorOptionTitleActive: {
      color: colors.primary,
    },
    selectorBadge: {
      borderRadius: 999,
      backgroundColor: colors.primary,
      paddingHorizontal: SPACING.sm,
      paddingVertical: 6,
    },
    selectorBadgeText: {
      color: colors.primaryText,
      fontSize: 11,
      fontWeight: "700",
    },
    buttonRow: {
      gap: SPACING.sm,
    },
    buttonGroup: {
      gap: SPACING.sm,
    },
    primaryButton: {
      minHeight: CONTROL_SIZE.inputHeight,
      borderRadius: RADIUS.md,
      backgroundColor: colors.primary,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: SPACING.md,
      width: "100%",
    },
    primaryButtonText: {
      color: colors.primaryText,
      fontSize: FONT_SIZE.button,
      fontWeight: "700",
    },
    secondaryButton: {
      minHeight: CONTROL_SIZE.inputHeight,
      borderRadius: RADIUS.md,
      borderWidth: 1,
      borderColor: outlineColor,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: colors.surface,
      paddingHorizontal: SPACING.md,
      width: "100%",
    },
    secondaryButtonText: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
      textAlign: "center",
    },
    backButton: {
      width: "100%",
    },
    buttonDisabled: {
      opacity: 0.6,
    },
  });
};
