import { useLocalSearchParams, useRouter } from "expo-router";
import {
  collection,
  doc,
  getDoc,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  type DocumentData,
} from "firebase/firestore";
import { useEffect, useMemo, useState } from "react";
import {
  ActivityIndicator,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";

import {
  COLORS,
  CONTROL_SIZE,
  FONT_SIZE,
  RADIUS,
  SPACING,
} from "@/constants/theme";
import {
  CATEGORIES_COLLECTION,
  POSTS_COLLECTION,
  createSlug,
  mapCategoryRecord,
  mapPostRecord,
  type CategoryRecord,
  type PostRecord,
  type PostStatus,
} from "@/lib/content";
import { firestore } from "@/lib/firebase";
import { useAuth } from "@/providers/auth-provider";
import RichTextEditor, {
  type RichTextEditorValue,
} from "@/components/rich-text-editor";

const POST_STATUSES: PostStatus[] = ["draft", "published"];
const HTML_TAG_PATTERN = /<\/?[a-z][\s\S]*>/i;

const resolvePostId = (value: string | string[] | undefined) =>
  typeof value === "string" ? value : "";

const toHtmlContent = (value: string) => {
  const normalized = value.trim();
  if (!normalized) {
    return "";
  }

  if (HTML_TAG_PATTERN.test(normalized)) {
    return normalized;
  }

  const escaped = normalized
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  return `<p>${escaped.replace(/\n/g, "<br/>")}</p>`;
};

const extractPlainText = (value: string) =>
  value
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&#39;/gi, "'")
    .replace(/&quot;/gi, '"')
    .replace(/\u200B/g, "")
    .replace(/\s+/g, " ")
    .trim();

export default function AdminPostEditScreen() {
  const router = useRouter();
  const { postId: postIdParam } = useLocalSearchParams<{ postId?: string }>();
  const { user } = useAuth();

  const postId = resolvePostId(postIdParam);
  const isEditing = Boolean(postId);

  const [categories, setCategories] = useState<CategoryRecord[]>([]);
  const [posts, setPosts] = useState<PostRecord[]>([]);
  const [isLoadingCategories, setIsLoadingCategories] = useState(true);
  const [isLoadingPost, setIsLoadingPost] = useState(isEditing);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const [title, setTitle] = useState("");
  const [slugInput, setSlugInput] = useState("");
  const [isSlugManuallyEdited, setIsSlugManuallyEdited] = useState(false);
  const [contentHtml, setContentHtml] = useState("");
  const [contentPlainText, setContentPlainText] = useState("");
  const [editorResetKey, setEditorResetKey] = useState(0);
  const [category, setCategory] = useState("");
  const [status, setStatus] = useState<PostStatus>("draft");
  const [isCategoryMenuOpen, setIsCategoryMenuOpen] = useState(false);

  const autoGeneratedSlug = useMemo(() => createSlug(title), [title]);
  const selectedCategoryLabel = useMemo(() => {
    const selectedCategory = categories.find((item) => item.slug === category);
    if (!selectedCategory) {
      return "";
    }
    return `${selectedCategory.name} (${selectedCategory.slug})`;
  }, [categories, category]);

  useEffect(() => {
    const categoriesQuery = query(
      collection(firestore, CATEGORIES_COLLECTION),
      orderBy("name", "asc"),
    );
    const postsQuery = query(
      collection(firestore, POSTS_COLLECTION),
      orderBy("createDate", "desc"),
    );

    const unsubscribeCategories = onSnapshot(
      categoriesQuery,
      (snapshot) => {
        setCategories(
          snapshot.docs.map((item) =>
            mapCategoryRecord(item.id, item.data() as DocumentData),
          ),
        );
        setIsLoadingCategories(false);
      },
      () => {
        setIsLoadingCategories(false);
        setError("Unable to load categories.");
      },
    );

    const unsubscribePosts = onSnapshot(
      postsQuery,
      (snapshot) => {
        setPosts(
          snapshot.docs.map((item) =>
            mapPostRecord(item.id, item.data() as DocumentData),
          ),
        );
      },
      () => {
        setError("Unable to load posts for validation.");
      },
    );

    return () => {
      unsubscribeCategories();
      unsubscribePosts();
    };
  }, []);

  useEffect(() => {
    if (!isEditing) {
      setIsLoadingPost(false);
      return;
    }

    let active = true;

    const hydratePost = async () => {
      try {
        const postRef = doc(firestore, POSTS_COLLECTION, postId);
        const snapshot = await getDoc(postRef);

        if (!snapshot.exists()) {
          if (active) {
            setError("Post not found.");
          }
          return;
        }

        const rawData = snapshot.data() as DocumentData;
        const post = mapPostRecord(snapshot.id, rawData);

        if (!active) {
          return;
        }

        setTitle(post.title);
        setSlugInput(post.slug);
        setIsSlugManuallyEdited(post.slug !== createSlug(post.title));
        const hydratedContentHtml =
          typeof rawData.contentHtml === "string" && rawData.contentHtml.trim()
            ? rawData.contentHtml
            : toHtmlContent(post.content);
        const hydratedPlainText =
          post.content.trim() || extractPlainText(hydratedContentHtml);
        setContentHtml(hydratedContentHtml);
        setContentPlainText(hydratedPlainText);
        setEditorResetKey((value) => value + 1);
        setCategory(post.category);
        setStatus(post.status);
        setError("");
      } catch {
        if (active) {
          setError("Unable to load post details.");
        }
      } finally {
        if (active) {
          setIsLoadingPost(false);
        }
      }
    };

    void hydratePost();

    return () => {
      active = false;
    };
  }, [isEditing, postId]);

  useEffect(() => {
    if (!isSlugManuallyEdited) {
      setSlugInput(autoGeneratedSlug);
    }
  }, [autoGeneratedSlug, isSlugManuallyEdited]);

  useEffect(() => {
    if (!categories.length) {
      setIsCategoryMenuOpen(false);
      return;
    }

    if (!category || !categories.some((item) => item.slug === category)) {
      setCategory(categories[0].slug);
    }
  }, [categories, category]);

  const isLoadingInitial = isLoadingCategories || isLoadingPost;

  const getUniqueSlug = (base: string) => {
    const normalizedBase = base || "post";
    let candidate = normalizedBase;
    let suffix = 1;

    while (
      posts.some((item) => item.slug === candidate && item.id !== postId)
    ) {
      candidate = `${normalizedBase}-${suffix}`;
      suffix += 1;
    }

    return candidate;
  };

  const clearFeedback = () => {
    setError("");
    setSuccess("");
  };

  const handleTitleChange = (value: string) => {
    setTitle(value);
    clearFeedback();
  };

  const handleSlugChange = (value: string) => {
    setSlugInput(value);
    const normalized = createSlug(value);
    setIsSlugManuallyEdited(
      Boolean(value.trim()) && normalized !== autoGeneratedSlug,
    );
    clearFeedback();
  };

  const handleResetSlug = () => {
    setIsSlugManuallyEdited(false);
    setSlugInput(autoGeneratedSlug);
    clearFeedback();
  };

  const handleSelectCategory = (value: string) => {
    setCategory(value);
    setIsCategoryMenuOpen(false);
    clearFeedback();
  };

  const handleSave = async () => {
    const trimmedTitle = title.trim();
    const plainContent = contentPlainText.trim();
    const htmlContent = contentHtml.trim() || toHtmlContent(plainContent);
    const normalizedCategory = category.trim().toLowerCase();
    const normalizedStatus: PostStatus =
      status === "published" ? "published" : "draft";
    const slugBase = createSlug(slugInput || trimmedTitle);

    if (!trimmedTitle) {
      setError("Title is required.");
      return;
    }

    if (!plainContent) {
      setError("Blog content is required.");
      return;
    }

    if (!categories.length) {
      setError("Create at least one category before saving a post.");
      return;
    }

    if (!slugBase) {
      setError("Slug must include letters or numbers.");
      return;
    }

    if (
      !normalizedCategory ||
      !categories.some((item) => item.slug === normalizedCategory)
    ) {
      setError("Select a valid category from the dropdown.");
      return;
    }

    try {
      setIsSubmitting(true);
      clearFeedback();

      if (isEditing) {
        const uniqueSlug = getUniqueSlug(slugBase);
        const postRef = doc(firestore, POSTS_COLLECTION, postId);

        await setDoc(
          postRef,
          {
            id: postId,
            slug: uniqueSlug,
            title: trimmedTitle,
            content: plainContent,
            contentHtml: htmlContent,
            category: normalizedCategory,
            status: normalizedStatus,
            uploadDate: serverTimestamp(),
            updatedBy: user?.uid ?? "",
            updatedByEmail: user?.email ?? "",
          },
          { merge: true },
        );

        setSuccess("Post updated in Firebase.");
      } else {
        const postRef = doc(collection(firestore, POSTS_COLLECTION));
        const uniqueSlug = `${getUniqueSlug(slugBase)}-${postRef.id.slice(0, 6)}`;

        await setDoc(postRef, {
          id: postRef.id,
          slug: uniqueSlug,
          title: trimmedTitle,
          content: plainContent,
          contentHtml: htmlContent,
          category: normalizedCategory,
          status: normalizedStatus,
          createDate: serverTimestamp(),
          uploadDate: serverTimestamp(),
          createdBy: user?.uid ?? "",
          createdByEmail: user?.email ?? "",
        });

        setSuccess("Post created in Firebase.");
      }

      router.replace("/admin/posts");
    } catch (saveError) {
      if (saveError instanceof Error && saveError.message) {
        setError(saveError.message);
      } else {
        setError("Unable to save post to Firebase.");
      }
    } finally {
      setIsSubmitting(false);
    }
  };

  if (isLoadingInitial) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color={COLORS.primary} />
      </View>
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>
        {isEditing ? "Edit Post" : "Create Post"}
      </Text>
      <Text style={styles.subtitle}>
        Save will write post data to Firebase collection `posts`.
      </Text>

      {error ? <Text style={styles.error}>{error}</Text> : null}
      {success ? <Text style={styles.success}>{success}</Text> : null}

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Post Details</Text>

        <Text style={styles.label}>Title *</Text>
        <View style={styles.inputWrap}>
          <TextInput
            value={title}
            onChangeText={handleTitleChange}
            placeholder="Enter title"
            placeholderTextColor={COLORS.mutedText}
            style={styles.input}
          />
        </View>

        <View style={styles.inlineRow}>
          <Text style={styles.label}>Slug</Text>
          <Pressable onPress={handleResetSlug}>
            <Text style={styles.linkText}>Reset Auto Slug</Text>
          </Pressable>
        </View>
        <View style={styles.inputWrap}>
          <TextInput
            value={slugInput}
            onChangeText={handleSlugChange}
            placeholder="Auto-generated from title"
            placeholderTextColor={COLORS.mutedText}
            autoCapitalize="none"
            style={styles.input}
          />
        </View>
        <Text style={styles.helperText}>
          Slug title se auto-generate hota hai, manually override bhi kar sakte
          ho.
        </Text>

        <Text style={styles.label}>Blog Content *</Text>
        <RichTextEditor
          key={editorResetKey}
          initialHtml={contentHtml}
          placeholder="Write your blog post here..."
          onChange={(value: RichTextEditorValue) => {
            setContentHtml(value.html);
            setContentPlainText(value.plainText);
            clearFeedback();
          }}
        />
        <Text style={styles.helperText}>
          Rich text editor se headings, lists, bold, italic aur alignment use
          kar sakte ho.
        </Text>

        <Text style={styles.label}>Status</Text>
        <View style={styles.chipRow}>
          {POST_STATUSES.map((item) => (
            <Pressable
              key={item}
              style={[
                styles.chip,
                status === item ? styles.chipActive : undefined,
              ]}
              onPress={() => setStatus(item)}
            >
              <Text
                style={[
                  styles.chipText,
                  status === item ? styles.chipTextActive : undefined,
                ]}
              >
                {item === "draft" ? "Draft" : "Published"}
              </Text>
            </Pressable>
          ))}
        </View>

        <Text style={styles.label}>Category *</Text>
        <View
          style={[
            styles.dropdownWrap,
            isCategoryMenuOpen ? styles.dropdownWrapActive : undefined,
          ]}
        >
          <Pressable
            style={[
              styles.dropdownTrigger,
              (!categories.length || isSubmitting) && styles.dropdownDisabled,
            ]}
            onPress={() => {
              if (!categories.length || isSubmitting) {
                return;
              }
              setIsCategoryMenuOpen((value) => !value);
            }}
            disabled={!categories.length || isSubmitting}
          >
            <Text
              style={[
                styles.dropdownValue,
                !selectedCategoryLabel && styles.dropdownPlaceholder,
              ]}
            >
              {selectedCategoryLabel ||
                (isLoadingCategories
                  ? "Loading categories..."
                  : "Select category")}
            </Text>
            <Text style={styles.dropdownIcon}>
              {isCategoryMenuOpen ? "^" : "v"}
            </Text>
          </Pressable>

          {isCategoryMenuOpen ? (
            <View style={styles.dropdownMenu}>
              <ScrollView style={styles.dropdownList} nestedScrollEnabled>
                {categories.map((item) => (
                  <Pressable
                    key={item.id}
                    style={[
                      styles.dropdownOption,
                      category === item.slug
                        ? styles.dropdownOptionActive
                        : undefined,
                    ]}
                    onPress={() => handleSelectCategory(item.slug)}
                  >
                    <Text
                      style={[
                        styles.dropdownOptionTitle,
                        category === item.slug
                          ? styles.dropdownOptionTitleActive
                          : undefined,
                      ]}
                    >
                      {item.name}
                    </Text>
                    <Text style={styles.dropdownOptionMeta}>{item.slug}</Text>
                  </Pressable>
                ))}
              </ScrollView>
            </View>
          ) : null}
        </View>

        <View style={styles.buttonRow}>
          <Pressable
            style={({ pressed }) => [
              styles.primaryButton,
              pressed && styles.buttonPressed,
              isSubmitting && styles.buttonDisabled,
            ]}
            onPress={handleSave}
            disabled={isSubmitting}
          >
            {isSubmitting ? (
              <ActivityIndicator size="small" color={COLORS.primaryText} />
            ) : (
              <Text style={styles.primaryButtonText}>
                {isEditing ? "Update Post" : "Create Post"}
              </Text>
            )}
          </Pressable>

          <Pressable
            style={({ pressed }) => [
              styles.secondaryButton,
              pressed && styles.buttonPressed,
            ]}
            onPress={() => router.replace("/admin/posts")}
            disabled={isSubmitting}
          >
            <Text style={styles.secondaryButtonText}>Back to Post List</Text>
          </Pressable>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.background,
  },
  container: {
    padding: SPACING.xl,
    backgroundColor: COLORS.background,
    gap: SPACING.md,
  },
  title: {
    fontSize: FONT_SIZE.title,
    fontWeight: "700",
    color: COLORS.text,
  },
  subtitle: {
    color: COLORS.mutedText,
    fontSize: FONT_SIZE.body,
  },
  error: {
    color: COLORS.danger,
    fontSize: 13,
  },
  success: {
    color: "#166534",
    fontSize: 13,
  },
  section: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    gap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.text,
  },
  inlineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  helperText: {
    color: COLORS.mutedText,
    fontSize: 12,
  },
  linkText: {
    color: COLORS.primary,
    fontSize: 12,
    fontWeight: "600",
  },
  inputWrap: {
    minHeight: CONTROL_SIZE.inputHeight,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    justifyContent: "center",
  },
  input: {
    color: COLORS.text,
    fontSize: FONT_SIZE.button,
  },
  label: {
    color: COLORS.text,
    fontWeight: "600",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  chip: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 999,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    backgroundColor: COLORS.surface,
  },
  chipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chipText: {
    color: COLORS.text,
    fontSize: 13,
    fontWeight: "600",
  },
  chipTextActive: {
    color: COLORS.primaryText,
  },
  dropdownWrap: {
    position: "relative",
  },
  dropdownWrapActive: {
    zIndex: 10,
  },
  dropdownTrigger: {
    minHeight: CONTROL_SIZE.inputHeight,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: SPACING.sm,
  },
  dropdownDisabled: {
    opacity: 0.6,
  },
  dropdownValue: {
    color: COLORS.text,
    fontSize: FONT_SIZE.button,
    flex: 1,
  },
  dropdownPlaceholder: {
    color: COLORS.mutedText,
  },
  dropdownIcon: {
    color: COLORS.mutedText,
    fontSize: 12,
    fontWeight: "700",
  },
  dropdownMenu: {
    marginTop: SPACING.xs,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  dropdownList: {
    maxHeight: 180,
  },
  dropdownOption: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    gap: 2,
  },
  dropdownOptionActive: {
    backgroundColor: "#EFF6FF",
  },
  dropdownOptionTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "600",
  },
  dropdownOptionTitleActive: {
    color: COLORS.primary,
  },
  dropdownOptionMeta: {
    color: COLORS.mutedText,
    fontSize: 12,
  },
  buttonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: SPACING.sm,
  },
  primaryButton: {
    flex: 1,
    minHeight: CONTROL_SIZE.inputHeight,
    borderRadius: RADIUS.md,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: SPACING.md,
  },
  primaryButtonText: {
    color: COLORS.primaryText,
    fontSize: FONT_SIZE.button,
    fontWeight: "700",
  },
  secondaryButton: {
    flex: 1,
    minHeight: CONTROL_SIZE.inputHeight,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
    paddingHorizontal: SPACING.md,
  },
  secondaryButtonText: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  buttonPressed: {
    opacity: 0.9,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
});
